### PR TITLE
Updated to latest cowboy

### PR DESCRIPTION
**Pull request by excavador**
Updated to latest cowboy: "version" changed from {1,0} and {1,1} to 'HTTP/1.0' and 'HTTP/1.1'.

### CODE REVIEW

**Comment by excavador** [comment]
What the typo do you mean?

**Comment by excavador** [comment]
Oh, I see. Just one minute

**Comment by excavador** [comment]
Fixed

**Comment by dvv** [comment]
Merged. Thanks!

**Pull request merged**
