### PR TITLE
Callback hook

### PR DESCRIPTION
**Pull request by jtmoulia**
Allows provider configuration to specify `callback_hooks`, an array of modules which implement the `cowboy_social_hook` behavior. After receiving the token, either via the callback endpoint or authorization code, each callback module's `execute` function will be called in the order configured.

Still requires documentation -- I'll add it if this direction sounds good!

For dvv/social#2.

### CODE REVIEW

**Comment by dvv** [comment]
How can I look at the net commit?

**Comment by jtmoulia** [comment]
Does [this](https://github.com/dvv/social/pull/3/files) work?

**Comment by dvv** [comment]
Aha. Much better )

**Comment by dvv** [comment]
Merged. Thanks

**Pull request merged**
